### ISSUE TITLE
Missing dependencies in newest version

### ISSUE THREAD

**Issue by miroli** [semio/ddf_utils#114]
Not sure what causes this but upgrading from 0.5.1 to 0.6.0, ddf_utils fails at import due to missing dependencies. I first used pipenv, installed the package and tried importing it in a new terminal and got this error message.

```
[...]/python3.7/site-packages/ddf_utils/chef/helpers.py", line 17, in <module>
    from joblib import Memory
ModuleNotFoundError: No module named 'joblib'
```

I then tried the same thing with pip, and got a similar error.

```
[...]/python3.7/site-packages/ddf_utils/model/ddf.py", line 8, in <module>
    import attr
ModuleNotFoundError: No module named 'attr'
```

**Comment by semio** [comment]
Hi @miroli thanks for reporting the issue. I will fix it and push a new version soon.

**Comment by semio** [comment]
I just pushed version 0.6.1, could you try again to install? Both pipenv and pip should work.

**Comment by miroli** [comment]
0.6.2 works, great! Thank you :)
