### ISSUE TITLE
Problem with attrs in 0.6.2 

### ISSUE THREAD

**Issue by lapidus** [semio/ddf_utils#115]
The requirements specifies `attr` but it seems the library is `attrs`?
https://pypi.org/project/attrs/

![image](https://user-images.githubusercontent.com/66601/53809297-b18b2600-3f54-11e9-8e21-c26fd04ea95d.png)

**Comment by semio** [comment]
Oh, you are right. I will fix this and push 0.6.3. Interestingly travis-ci didn't report this issue.

**Comment by semio** [comment]
@lapidus if you still encounter this problem, you might need to uninstall `attr` first
