### ISSUE TITLE
outdated link for "DDF Model"

### ISSUE THREAD

**Issue by armijnhemel** [semio/ddf_utils#117]
In README.md the link for "DDF Model" points to https://github.com/open-numbers/wiki/wiki/Introduction-to-DDF but that seems to be a 404. I could not find a newer link.

**Comment by semio** [comment]
@armijnhemel: The wiki pages were moved to a separated website here: https://open-numbers.github.io/ddf.html. I will fix the broken link. Thanks for reporting the issue :)
