### ISSUE TITLE
Disable progress bar

### ISSUE THREAD

**Issue by miroli** [semio/ddf_utils#118]
Is there any way to disable the tqdm progress bar when running `ddf_utils.io.dump_json()`?

**Comment by miroli** [comment]
(Can't seem to edit my original post)

I meant disabling the progress bar when running `ddf_utils.package.create_package()`.

**Comment by semio** [comment]
@miroli currently you can disable tqdm by setting the logging level to DEBUG. But this will result in many debugging output. 

Adding more options to control command output is on my todo list. I will work on this today, to add option to enable/disable progress bar

**Comment by semio** [comment]
@miroli I made following changes:

- cli: by default it will not show a progress bar, and you can enable it by passing `-p` to `ddf create_datapackage`
- library function: added `progress_bar` parameter to create_datapackage(), which can be set to True/False. 

Is this working for your use case? Feel free to let me know if you have more suggestions.

**Comment by miroli** [comment]
@semio Thanks, that was great! It's working perfectly.
