### ISSUE TITLE
Version mismatch in dependencies

### ISSUE THREAD

**Issue by miroli** [semio/ddf_utils#121]
My local environment is failing due to a mismatch in the requirements. After some investigation, I think I've found the culprit.

ddf_utils requires [click<7](https://github.com/semio/ddf_utils/blob/d419f98c64cdf40f30226883c260693bda7ede79/requirements.txt#L8) and the latest version of [cookiecutter](https://github.com/semio/ddf_utils/blob/d419f98c64cdf40f30226883c260693bda7ede79/requirements.txt#L7). However, the latest version of `cookiecutter` requires [click>=7](https://github.com/cookiecutter/cookiecutter/blob/master/setup.py#L29). These requirements are not compatible.

**Comment by semio** [comment]
@miroli Thanks for reporting, Click 7 introduced breaking changes so I limited it to older version. I will take a look at how much work to be done in order to adapt to Click 7

**Comment by semio** [comment]
The breaking change for Click 7 is that it will automatically convert underscores to dashes in command names, so with Click 7 `ddf create_datapackage` become `ddf create-datapackage` and the underscore version will fail. I can explicitly set the name to avoid this. 

I think using dashes is just conventions and it doesn't bring advantages but only breaks backward compatibility for ddf_utils. So I will update the dependency to click 7 and set the names to underscore version.
