### ISSUE TITLE
recipe procedure: align

### ISSUE THREAD

**Issue by semio** [semio/ddf_utils#3]
## Reason

The same entity may have different keys in different datasets. For example, the key for country entity, may be the iso code in one dataset, while in the other dataset it may be the alphanumeric form of the country name. When creating a new dataset we may want to use the datapoints from one and country key from other. so we need a procedure to change the country in datapoints to match the other dataset.

EDIT: I found this is an automate version of `translate_column`. `translate_column` takes a dictionary as input and `align` generate the dictionary on the fly. Not sure if it's good to combine this function into translate_column. 
## API

`align` procedure translate the index column in a ingredient to make it align with an other ingredient.

the `align` procedure accepts following options:
- `ingredients`: the target ingredient to translate
- `search_cols`: the columns to search for values in base ingredient
- `to_find`: the column in target ingredient contains values to search
- `to_replace`: after finishing search, replace the column with new value

**Comment by semio** [comment]
example:

https://github.com/semio/ddf--gapminder--systema_globalis/blob/feature/autogenerated/etl/recipes/recipe_gapminder.yaml

This recipe replace the country column in datapoints to match the GW geo entity.

**Comment by jheeffer** [comment]
How could this be joined with `translate_column` in a clear API?

```
{
  procedure: 'translate_column',
  ingredient: 'wdi-countries',              // ingredient which will be translated
  column: 'country',                        // column in ingredient which will be translated
  target_column: 'geo',                     // column where translations will be written to. 
                                            // Overwrites when target_column already exists. 
                                            // Creates new column when target_column does not exist. 
                                            // Defaults to 'column' value.
  dictionary: { 
    ingredient: 'gw-entities',              // ingredient from which to build dictionary
    key: 'name' || ['name','alt1','alt2'],  // columns which form dictionary keys
    value: 'geo'                            // column which forms dictionary value
  },
  dictionary: 'path/to/dictionary.json'     // path to a json file containing a dictionary
  dictionary: {                             // inline dictionary
    China: 'chn',
    Sweden: 'swe'
  }
  not_found: 'error' || 'drop' || 'include',  // action on row when column contains value not in dictionary keys. Defaults to include.
}
```

Questions:

1. Does this seem a clear API to you? Does it allow for the same functionality as translate_column and align have now?
2. How to solve the ambiguity of dictionaries with an object value. 
  
    2.1 Maybe three different dictionary properties? `dictionary_from_file`, `dictionary_from_ingredient`, `dictionary_inline`?
    2.2 `dictionary: { type: 'inline' || 'file' || 'ingredient', .. }`
    2.3 Something else?

**Comment by jheeffer** [comment]
p.s. 

here: https://github.com/semio/ddf_utils/issues/28
and in the code recipe code I saw the `base` option for `translate_column` which seems to overlap with `align`. Is that correct?

**Comment by semio** [comment]
yes, @jheeffer your suggestion looks clear. I agree we can join this function to translation_column. I think we should put `dictionary` inside `options`, as what we do in other functions:

```json
{
  procedure: 'translate_column',
  ingredient: 'wdi-countries',              // ingredient which will be translated
  options: {
    column: 'country',                        // column in ingredient which will be translated
    target_column: 'geo',                     // column where translations will be written to. 
                                            // Overwrites when target_column already exists. 
                                            // Creates new column when target_column does not exist. 
                                            // Defaults to 'column' value.
    dictionary: { 
      ingredient: 'gw-entities',              // ingredient from which to build dictionary
      key: 'name' || ['name','alt1','alt2'],  // columns which form dictionary keys
      value: 'geo'                            // column which forms dictionary value
  }
}

**Comment by jheeffer** [comment]
Alright, options is good then. I see you prefer key/value over from/to. I would call it dictionary_type though, to make the link to dictionary clear.
Is `dictionary_type` mandatory or has it a default/is it smart depending on dictionary object's properties?

**Comment by semio** [comment]
Yes, `dictionary_type` can be smart depending on dictionary object. We can skip this parameter.

**Comment by jheeffer** [comment]
I think this is ready for implementation!
