### ISSUE TITLE
Chef, align: Handle ambiguity in translation dictionaries

### ISSUE THREAD

**Issue by jheeffer** [semio/ddf_utils#34]
Imagine a dataset with entity-id `congo`.
It has to be aligned with entities of another dataset, which has `cod` ( Democratic Republic of the Congo ) and `cog` ( Republic of the Congo ) (or even more from https://en.wikipedia.org/wiki/Congo). There is an ambiguity as to what entity `congo` should be aligned with, `cod` or `cog`. 
The script is aware of this ambiguity through it's dictionary:
1. data-dictionary: Both `cod` and `cog` have `congo` as a synonym in one of their synonym columns 
2. json or inline dictionary: `congo` has an array-value with both `cog` and `cod` as items.

Possible behaviour when this situation is found:

"Procedure `align` found n possible entities for `congo`. Please choose the correct entity to align `congo` with for the rest of the execution of the recipe:"
1) cod
2) cog
3) do not include "congo"
4) cancel chef execution

**Comment by semio** [comment]
I have added above behaviour to chef, and added an option 'ambiguity' to `translate_column` to control the behavior. See [updated document](https://ddf-utils.readthedocs.io/en/dev/recipe.html#translate-column).

The prompt text is set to:

```
Please choose the correct entity to align *Congo* with for the rest of the execution of the recipe:
1: cod
2: cog
Please select a value (1 ~ 2), or "n" to skip, "q" to quit:
```
