### ISSUE TITLE
pip install on windows fails (easily fixable)

### ISSUE THREAD

**Issue by jheeffer** [semio/ddf_utils#38]
### Environment
Windows 10
Python 3.5.2
Pip 9.0.1 and pip 8.something (which comes with python 3.5.2 install)

### Reproduce
1. Have python installed on a path with a space. In my case: `C:\Program Files (x86)\Python35-32`
2. Run `pip3 install git+https://github.com/semio/ddf_utils.git`
3. Run `ddf`

### Result:
```
D:\github\open-numbers\ddf--gapminder--systema_globalis>ddf
failed to create process.
```

### Expected result:
Overview of ddf utils functionality

People at `pip` repo seem to know about it, but it still appears to pop up?
https://github.com/pypa/pip/issues/2783

### Quick manual fix:
1. Open `Scripts/ddf-script.py` in python install folder
2. Change first line to have quotes around path
E.g. 
`#!c:\program files (x86)\python35-32\python.exe`
to
`#!"c:\program files (x86)\python35-32\python.exe"`
3. run `ddf` 
4. Profit.

### possibly needed for quick fix:

1. Give modify permissions to users in script folder:
![](https://cloud.githubusercontent.com/assets/1596071/20533573/52f68f78-b0de-11e6-9859-8b5d5d672667.png)

**Comment by semio** [comment]
I will try the work around in https://github.com/tomduck/pandoc-eqnos/blob/master/setup.py

**Comment by semio** [comment]
hi @jheeffer ,

Can you try updating setuptool too? I think this was fixed in https://github.com/pypa/setuptools/pull/616

just run `pip3 install -U setuptools` and try the ddf command again.

**Comment by jheeffer** [comment]
update setuptools fixed it indeed. Please add this to readme for windows users : )!
