### ISSUE TITLE
recipe procedure: groupby

### ISSUE THREAD

**Issue by semio** [semio/ddf_utils#4]
## Reason

Sometimes we want to group a datapoint by some of its domains and calculate a new datapoint. For example we have population for age 0, 1, 2, 3, ... 10 for each country and we want to calculate population_between_0_and_10. Then we need to have a procedure to group the datapoint by country/year and sum up all data.
## API

`groupby` groups the data in a ingredient by a key/keys and return aggregated results as new ingredient.

`groupby` accepts following options:
- `by`: the key/keys to group
- `aggregate`: the function to calculate the result.

**Comment by semio** [comment]
need to support more operations other than aggregate functions. like cumsum() and other custom functioins.

**Comment by semio** [comment]
close this in favour of #19. It's not very good to add accumulate functions to groupby function because it's not the nature usage for groupby.

**Comment by jheeffer** [comment]
I disagree, group_by (almost) always goes together with aggregate functions.

| geo | year | population  |
| ------------- |:-------------:| -----:|
| swe | 2015 | 10 |
| swe | 2016 | 11 |
| swe | 2017 | 11 |
| chn | 2015 | 10 |
| chn | 2016 | 21 | 

Let's look at SQL:
Each column that is selected has to be mentioned either in group by or in an aggregate function.

### GROUP BY all columns

If all columns are mentioned in group by, you'll get the same table as before (i.e. identity function).

sql: `SELECT geo, year, population GROUP BY geo, year, population`

| geo | year | population  |
| ------------- |:-------------:| -----:|
| swe | 2015 | 10 |
| swe | 2016 | 11 |
| swe | 2017 | 11 |
| chn | 2015 | 10 |
| chn | 2016 | 21 | 

This is pretty useless

### GROUP BY subset of columns

sql: `SELECT year, population GROUP BY year, population`

 year | population  |
| -------------:| -----:|
| 2015 | 10 |
| 2016 | 11 |
| 2017 | 11 |
| 2016 | 21 | 

I don't see this as a use case for us.

### GROUP BY subset of columns with aggregate function

sql: `SELECT geo, avg(population) GROUP BY geo`

| geo | avg(population) |
| ------------- | -----:|
| swe | 10.66 |
| chn | 15.5 |

This is the normal use case that we will use

sql: `SELECT geo, avg(year), population GROUP BY geo, population`

| geo | avg(year) | population |
| ------------- | -----:| -----:|
| swe | 2015 | 10 |
| swe | 2016.5 | 11 |
| chn | 2015 | 10 |
| chn | 2016 | 21 | 

This is a weird use case which we will probably not use.

Now we have to see how we put this in a recipe.

**Comment by semio** [comment]
Yes, I agree that group by always run with aggregate functions. The API described on the top is supported in Chef. I am thinking about another type of functions here on the last 2 comments. Sorry for the misleading...

For now if we want to group by geo, time and get average population for each country, we can write recipe like this:

```yaml
procedure: groupby
ingredients: [datapoints-population]
options:
    by:
        - geo
    aggregate: mean
```

But the column to do aggregate is fixed to the datapoint column, which is population in this example.

Other than aggregate functions like sum, mean, min, max etc, I was thinking about the **cumulative** functions like cumsum() or cumprod(). 

For example we have number of some event happened in one year:

| Time        | Occurrence      |    
| ------------- |------------|
| 1990      | 100  |
| 1991      | 20      | 
| 1992 | 321      |

Then the cumulative sum will be:

| Time        | Occurrence      |    
| ------------- |------------|
| 1990      | 100  |
| 1991      | 120      | 
| 1992 | 441      |

So actually we don't need to run group by. We just need to sort the `time` column in order. 

But in the SG dataset, where all datapoint have `geo` columns, we do want to run groupby first before running cumulative function... So I am in doubt that if we should add support for cumulative function in groupby procedure or we add cumulative procedure that have a groupby option. What do you think?

**Comment by jheeffer** [comment]
So I guess the following config would be good:

Name of procedure is still groupby. Another option would be aggregate, but it is possible to groupby without aggregating while aggregating always involves some kind of grouping.

Accumulate should be under groupby procedure. The below config also solves https://github.com/semio/ddf_utils/issues/25.


```js
{
  procedure: 'groupby'
  ingredient: 'gw-population'
  result: 'gw-population-aggregated'
  options: {
    aggregate: {
      year: {
        function: 'complex_function',
        foo: 'bar',
        another_parameter: 684
      }
      population: sum
    },
    group: geo || ['geo','and','more']
}
```

**Comment by jheeffer** [comment]
Oh, cross posted : )! Ah, cumulative functions vs aggregative functions... okay, interesting! Did you already need those in current recipes?

**Comment by semio** [comment]
Great, it looks good. I will implement it as you described.

**Comment by jheeffer** [comment]
Be sure that the `complex _function` case has the same syntax as in https://github.com/semio/ddf_utils/issues/25

so either like above or with `params: { foo: 'bar', another_parameter: 684 }` object

**Comment by semio** [comment]
I think both will work but I like the first more, because it's simpler

**Comment by semio** [comment]
close this in flavor of #25
