### ISSUE TITLE
new ideas about recipe

### ISSUE THREAD

**Issue by semio** [semio/ddf_utils#57]
Some days ago I came across [Hy](https://github.com/hylang/hy) language which brings Lisp like syntax to Python and I think using Lisp like syntax for recipe will bring benefits for recipe.

# what will it look like

using Lisp like syntax, we can write recipes like this: (below is just a prototype)

```clojure
(info :id "test_lisp_dataset"
      :name "test_lisp_dataset")

(config :dictionary_dir "./"
        :recipe_dir "./")

(include "other_parts.hy")

;; ingredients section
(ingredient :id "datapoints"
            :dataset "ddf--gapminder--systema_globalis"
            :key "geo, time"
            :value "*")

(ingredient :id "entities"
            :dataset "ddf--gapminder--geo_entity_domain"
            :key "geo"
            :value "*")

;; cooking section
(translate_header :ingredients ["datapoints"]
                  :options {
                              :dictionary "dict.json"
                           }
                  :result "out_ingredient")

;; serving section
(serving ["out_ingredient" "entities"])

```

This looks very similar to the recipe we are using.

# pros and cons

The advantage for using Hy is that, it's just Python. So you will get everything in Python: import other libraries, custom functions, if/else conditions, for loops, interactive debugging and so on.

on the other hand, using programming language will bring us risks:  using it incorrectly, or running recipes from untrusted source might break your computer. Also because Hy is still young, there might be bugs in it.

**Comment by semio** [comment]
see implementation on https://github.com/semio/ddf_utils/blob/6b5cae32c1fce814ecd265f28687a532de62b856/examples/example.hy and https://github.com/semio/ddf_utils/blob/6b5cae32c1fce814ecd265f28687a532de62b856/examples/housing_units.hy

**Comment by jheeffer** [comment]
I'm not sure yet what the benefits are. Why would we want to use programming language syntax in recipes? If we'd want that we can just use pure python scripts with a ddf procedures library. No need for introducing Hy?

**Comment by semio** [comment]
To be short: Hy can provide declarative syntax like the yaml recipe, and at the same time full access to programming features. 

There are times when we want to have some features in programming, such as what Harpal suggested here: https://github.com/semio/ddf_utils/issues/66#issuecomment-309748122

and as you said, for loop is an imperative programming concept. And recipe should be in declarative way. This is one of the reason why I want to try out Hy. Python is more imperative. For example if we need to add a new procedure to recipe, we might need to do 

```python
chef.add_procedure(procedure='filter', 
                   ingredients=['pop-by-age'], 
                   options={})
```
or we can make a function to make it more declarative:

```python
add_procedure(chef=chef
              procedure='filter', 
              ingredients=['pop-by-age'], 
              options={})
```

But you can see there are still variable assignments.  In Hy, you can do

```clojure
(add_procedure :chef chef
               :procedure "filter"
               :ingredients ["pop-by-age"]
               :options {})
```

The other reason is that, Hy has [macros](https://stackoverflow.com/questions/267862/what-makes-lisp-macros-so-special). That means we can define own syntax. If you check the [example hy recipe](https://github.com/semio/ddf_utils/blob/6b5cae32c1fce814ecd265f28687a532de62b856/examples/housing_units.hy) and the [same recipe in yaml](https://github.com/semio/ddf_utils/blob/6b5cae32c1fce814ecd265f28687a532de62b856/examples/housing_units.yaml), you can see how they look like each other. This is done by macros. I can make the hy version more like yaml version if necessary.

Though, what you said is right, we can just use pure python scripts with a ddf procedures library.
