### ISSUE TITLE
how to judge what entity_set a resource belongs to

### ISSUE THREAD

**Issue by semio** [semio/ddf_utils#61]
when we have entity_domain and entity_sets under the domain, we allow the entity_sets' primary key to be the entity_domain. So for geo domain, in country and street entity_set data the primary key can be `geo`. But then it comes to a problem, when we have the datapackage.json with non-standard naming, we can't determine from the datapackage.json which resource belongs to country, which to street.

```json
resources: [
    {"name": "entities_1",
     "path": "entities_1.csv",
     "schema": {
         "fields": [{"name": "geo"}, {"name": "name"}],
         "primaryKey": "geo"
       }
    },
    {"name": "entities_2",
     "path": "entities_2.csv",
     "schema": {
         "fields": [{"name": "geo"}, {"name": "name"}],
         "primaryKey": "geo"
       }
    }
]
```

**Comment by jheeffer** [comment]
This is why we have ddfSchema.

From there you can read for each key value pair (including one with entity sets) in which file they can be found. So geo will point to both country and street file. Country only to country file and street only to street file.

Then you still have to find which column actually contains the entity set. You know this from concepts files where you have which sets belong to which domains.

I have the feeling things still can go wrong though. There might be some unresolved ambiguity in this process.

**Comment by semio** [comment]
@jheeffer I have an idea. We can make use of the `is--` header. 

Because when `is--country` is True then we can say the entity belongs to `country` set, right? So we don't need to worry about which resource is under `country` set, we just read all resource under `geo` domain and filter entities where `is--country == True`.  This way works in our geo_entity_domain dataset. What's your opinion?

**Comment by jheeffer** [comment]
yes, indeed, this is part of creating ddfSchema too, but in reading the dataset you'll have to do this again. Create a lookup table of all geo's (from different files) with an overview of to what set(s) each geo belongs.

```
// fetch entity domain and entity set concepts
foreach (concepts_resources as resource)
	foreach (resource.data as row)
		if (row['concept_type'] == "entity_domain" OR row['concept_type'] == "entity_set")
			entityConcepts[row['concept']] = row; // entities['geo'] = { concept: "geo", concept_type: "entity_domain", ... }


entities = {};

// fetch set-membership details for every single entity in dataset
foreach (entities_resources as resource)

	// find the domain of this entity resource
	pk = resource.primaryKey[0];
	if (entityConcepts[pk]['concept_type'] == 'entity_domain')
		domain = pk;
	else 
		domain = entityConcepts[pk]['domain'];

	// find sets defined in this resource
	entity_set_fields = [];
	foreach (resource['fields'] as field)
		if (field.substring(0,4) == "is--")
			entity_set_fields.push(field)

	// get set membership per entity in this resource
	foreach (resource['data'] as row)
		if (!entities[domain])
			entities[domain] = {};
		if (!entities[domain][row[pk]])
			entities[domain][row[pk]] = new Set();
		entities[domain][row[pk]].add(domain);
		foreach (entity_set_fields as field)
			if (row[field])
				entities[domain][row[pk]].add(field.substring(4));

    // final format example
	// entities['geo']['usa'] = { geo, country, unstate }
	// entities['geo']['hkg'] = { geo, country, city }
	// entities['geo']['america'] = { geo, world_4region }
	// entities['gender']['male'] = { gender } 
	// entities['gender']['female'] = { gender }

```

**Comment by semio** [comment]
great, thanks for the detail explanation!
